/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconMdiEmail: typeof import('~icons/mdi/email.jsx')['default']
  const IconMdiGithub: typeof import('~icons/mdi/github.jsx')['default']
}
